### ISSUE TITLE
Notice: Undefined index: acf_field_group in Plugin_ACF.php on line 937

### ISSUE THREAD

**Issue by jasperrooduijn** [bonny/WordPress-Simple-History#145]
Ik keep getting this error when doing some dashboard based actions. For instance when saving a user profile and when syncing ACF field groups. Using WP version 4.9.6, Simple History 2.23.1 and ACF 5.6.10.

Notice: Undefined index: acf_field_group in plugins/simple-history/loggers/Plugin_ACF.php on line 937

**Comment by jasperrooduijn** [comment]
I also get this error when saving an excisting ACF fieldgroup with changed field settings.

Undefined variable: new_exists in plugins/simple-history/loggers/Plugin_ACF.php on line 898

**Comment by bonny** [comment]
Thanks for the report, will take a look at this and fix in next version.

**Comment by jasperrooduijn** [comment]
Great! Any news about a new update?

**Comment by bonny** [comment]
Check version 2.26, it should fix this.

**Comment by jasperrooduijn** [comment]
I am running the newest version now. This is 2.26.1. This fixes the errors above. Thanks. I also found some new errors when syncing a field group. See the errors below.

Notice: Undefined index: acf_field_group in simple-history/loggers/Plugin_ACF.php on line 954

Warning: Cannot modify header information - headers already sent by (output started at simple-history/loggers/Plugin_ACF.php:954) in wp-includes/pluggable.php on line 1216

**Comment by LordWhisper** [comment]
Version 2.26.1 still having the same incompatibility with ACF

AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Call to undefined function _acf_get_field_by_id() in /var/www/vhosts/DOMAIN/httpdocs/wp-content/plugins/simple-history/loggers/Plugin_ACF.php:374\nStack trace:\n#0 /var/www/vhosts/DOMAIN/httpdocs/wp-content/plugins/simple-history/loggers/Plugin_ACF.php(270): Plugin_ACF->add_acf_context(Array, 'added', Array, Array, Array, Array)\n#1 /var/www/vhosts/DOMAIN/httpdocs/wp-includes/class-wp-hook.php(286): Plugin_ACF->on_acf_save_post(559)\n#2 /var/www/vhosts/DOMAIN/httpdocs/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)\n#3 /var/www/vhosts/DOMAIN/httpdocs/wp-includes/plugin.php(453): WP_Hook->do_action(Array)\n#4 /var/www/vhosts/DOMAIN/httpdocs/wp-content/plugins/advanced-custom-fields-pro/includes/acf-form-functions.php(136): do_action('acf/save_post', 559)\n#5 /var/www/vhosts/DOMAIN/httpdocs/wp-content/plugins/advanced-custom-fields-pro/includes/forms/form-post.php(312): acf_save_post(559)\n...\n', referer: https://DOMAIN/wp-admin/post-new.php?post_type=auftritte&wp-post-new-reload=true&wp-post-new-reload=true

**Comment by bonny** [comment]
> Version 2.26.1 still having the same incompatibility with ACF
> 
> AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Call to undefined function _acf_get_field_by_id() in /var/www/vhosts/DOMAIN/httpdocs/wp-content/plugins/simple-history/loggers/Plugin_ACF.php:374\nStack trace:\n#0 /var/www/vhosts/DOMAIN/httpdocs/wp-

I think thas was another error and nothing to do with this issue. It is however fixed in version 2.29.2.
